### ISSUE TITLE
Reopening the issue on "play"

### ISSUE THREAD

**Issue by laurentbartholdi** [ISCAS-PMC/roll-library#5]
Thanks for the reply and the fix! However, I still get error messages, as below, and could not reopen the issue, hence a new one:
```bash
% java -jar ROLL.jar play
2025/01/15 20:46:16 [ info] ROLL for interactive play...
Please input the number of letters ('a'-'z'):
2
Please input the 1th letter:
a
Please input the 2th letter:
b
Resolving equivalence query for hypothesis (#Q=1)...
Learner: Leading Learner:
  || (ϵ, ϵ) |
=============
ϵ || -      |
=============
a || -      |
b || -      |

Progress Learner for ϵ:
  || ϵ      |
=============
ϵ || (0, B) |
=============
a || (0, B) |
b || (0, B) |

Is following automaton the unknown automaton: 1/0?
digraph {
  rankdir=LR;
  0 [label="0", shape = circle];
  0 -> 0 [label="b"];
  0 -> 0 [label="a"];
  1 [label="", shape = plaintext];
  1 -> 0 [label=""];
}

0
Now you have to input a counterexample for inequivalence.
please input stem:
a
You input a stem: a
please input loop:
b
You input a loop: b
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "counterexample" is null
	at roll.learner.nba.lomega.translator.TranslatorFDFA.getQuery(TranslatorFDFA.java:91)
	at roll.learner.nba.lomega.translator.TranslatorFDFAUnder.translate(TranslatorFDFAUnder.java:41)
	at roll.learner.nba.lomega.LearnerNBALOmega.refineHypothesis(LearnerNBALOmega.java:86)
	at roll.main.InteractiveMode.interact(InteractiveMode.java:76)
	at roll.main.ROLL.runPlayingMode(ROLL.java:186)
	at roll.main.ROLL.main(ROLL.java:79)
```

Thanks also for the pointer to Executor.class; I tried to modify it, but ran into the problem of printing an NBA to standard output. It would be much easier to print it is HOA format (since that format can easily be read into my program based on spot), but I get weird error messages when I create a parser with
```java
  Options options = new Options();
>   ParserHOA2 parser = new ParserHOA2(options);
   parser.print(automaton,System.out);
```
where java complains that options is protected (???) at the line marked >. Is there a better way to export an automaton?

**Comment by liyong31** [comment]
Hi, 

The issue is due to a wrong membership oracle was used in the interactive mode, which should be fixed now.
If you want to use HOA format, please use ParserHOA instead of ParserHOA2, which was meant to replace ParserHOA but is not ready yet. Note that ROLL only supports state-based Buchi condition in HOA format.

Please let me know if you have further questions.

Best,
Yong

**Comment by laurentbartholdi** [comment]
Still doesn't work:
```
java -jar ROLL.jar play
2025/01/19 12:28:13 [ info] ROLL for interactive play...
Please input the number of letters ('a'-'z'):
2
Please input the 1th letter:
a
Please input the 2th letter:
b
Is w-word (ϵ, a) in the unknown languge: 1/0
0
Is w-word (ϵ, b) in the unknown languge: 1/0
0
Resolving equivalence query for hypothesis (#Q=1)...
Learner: Leading Learner:
  || (ϵ, ϵ) |
=============
ϵ || -      |
=============
a || -      |
b || -      |

Progress Learner for ϵ:
  || ϵ      |
=============
ϵ || (0, B) |
=============
a || (0, B) |
b || (0, B) |

Is following automaton the unknown automaton: 1/0?
digraph {
  rankdir=LR;
  0 [label="0", shape = circle];
  0 -> 0 [label="b"];
  0 -> 0 [label="a"];
  1 [label="", shape = plaintext];
  1 -> 0 [label=""];
}

0
Now you have to input a counterexample for inequivalence.
please input stem:
a
You input a stem: a
please input loop:
b
You input a loop: b
Is w-word (a, b) in the unknown languge: 1/0
0
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "counterexample" is null
	at roll.learner.nba.lomega.translator.TranslatorFDFA.getQuery(TranslatorFDFA.java:91)
	at roll.learner.nba.lomega.translator.TranslatorFDFAUnder.translate(TranslatorFDFAUnder.java:41)
	at roll.learner.nba.lomega.LearnerNBALOmega.refineHypothesis(LearnerNBALOmega.java:86)
	at roll.main.InteractiveMode.interact(InteractiveMode.java:76)
	at roll.main.ROLL.runPlayingMode(ROLL.java:186)
	at roll.main.ROLL.main(ROLL.java:79)
```

About printing an NBA: I tried the following code snippet, in a class similar to 
```java

    private static Query<HashableValue> answerEquivalenceQuery(NBA hypothesis) {
        if(hypothesis != null) {
            List<String> apList = new ArrayList<>();
            for(int i = 0; i < hypothesis.getAlphabetSize(); i ++) {
                apList.add(hypothesis.getAlphabet().getLetter(i) + "");
            }
            System.out.println("TEST_AUTOMATON");
            Options options = new Options();
            ParserHOA parser = new ParserHOA(options); <------------------
            parser.print(hypothesis,System.out);
            System.out.println(hypothesis.toString(apList));
        }else {
            System.out.println("TEST_AUTOMATON2");
        }
        boolean answer = getInputAnswer();
        Word wordEmpty = hypothesis.getAlphabet().getEmptyWord();
        Query<HashableValue> ceQuery = new QuerySimple<>(wordEmpty, wordEmpty);
        ceQuery.answerQuery(new HashableValueBoolean(answer));
        return ceQuery;
    }
```
and at the line <------------------- there is a compilation error
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project roll-library: Compilation failure
[ERROR] /Users/laurent/roll-library/src/main/java/roll/main/NewMode.java:[198,32] constructor ParserHOA in class roll.parser.hoa.ParserHOA cannot be applied to given types;
[ERROR]   required: roll.main.Options
[ERROR]   found:    roll.main.Options
[ERROR]   reason: ParserHOA(roll.main.Options) has protected access in roll.parser.hoa.ParserHOA
```

**Comment by liyong31** [comment]
Hi,

When giving the counterexample (a, b), please make sure that the counterexample is in the symmetric difference of the conjectured automaton that ROLL outputs and your target automaton.
In your case, clearly, (a, b) should be accepting in order to work.

For the compilation error, please make sure that the constructor   public ParserHOA(Options options, String file)  is called where you specify your target automaton in file, otherwise the alphabet is undefined. You can modify the class ParserHOA to suit your need.   The options in ParserHOA cannot be modified and be accessed to other packages. 

Yong

**Comment by laurentbartholdi** [comment]
Sorry, I'm getting confused here.

My secret language is, say, {(ab)^omega}. Then it's not the language of the automaton given (which is the empty set, since there are no final states), and it doesn't contain a^omega, b^omega nor ab^omega. Or have I misunderstood the format (stem,loop)?

About the parser: if I try `ParserHOA(options,"")`, then there is an error message that file "" cannot be opened. I don't want to use the parser to parse the contents of a file, but rather to print an automaton. That's because parsing back an automaton in dot format is much harder than parsing it in HOA format.

**Comment by liyong31** [comment]
ROLL outputs an automaton accepting nothing. So, in your case, (ab)^{\omega} is the only word that is in the symmetric difference of your target language and the language of the conjecture automaton. The definition of symmetric difference means that the counterexample must either be accepted by the conjecture automaton or be in your target language, not both.

For the parser, then I am afraid that you need to modify ParserHOA to associate each letter (integer) with the boolean formula actually appearing on the transitions in automaton specified by the HOA format.

**Comment by liyong31** [comment]
Maybe you can use Spot to first translate the HOA file to a BA file and then it is straightforward to read BA file as an NBA in ROLL.

**Comment by laurentbartholdi** [comment]
OK, I can write a printer myself. I don't want to *read* automata in ROLL, but to *print* automata from ROLL.

About the play mode: please tell me if I understood correctly. When ROLL asks "Now you have to input a counterexample for inequivalence.", in fact, it doesn't need to ask whether "Is w-word (a, b) in the unknown languge: 1/0", because there is only one correct answer -- 1 if ab^omega is not accepted by the printed automaton, and 0 if it is.

**Comment by liyong31** [comment]
Yes, your understanding is correct. It asks this question because I did not add that check, or I trust the teacher to give consistent answers.

**Comment by liyong31** [comment]
Since there are no further replies, I will close this issue.
